name: Docker Build & Push

on:
  push:
    branches: [master]

jobs:
  build-fullstack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Fullstack App
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/idurar-fullstack:latest

  build-next-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Next.js App
        uses: docker/build-push-action@v5
        with:
          context: ./next-crud-app
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/idurar-next-app:latest
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}

  build-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Integration API
        uses: docker/build-push-action@v5
        with:
          context: ./nest-integ-api
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/idurar-integration:latest
